// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/(auth)/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/accounts-receivable/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounts-receivable">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/accounts-receivable/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/alerts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/alerts">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/alerts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/ap/payments/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ap/payments/new">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/ap/payments/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/approvals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/approvals">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/approvals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/ar-ap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ar-ap">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/ar-ap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/ar/payments-report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ar/payments-report">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/ar/payments-report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/ar/payments/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ar/payments/new">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/ar/payments/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/branches/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/branches">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/branches/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/cooperative/coordination/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cooperative/coordination">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/cooperative/coordination/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/cooperative/farms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cooperative/farms">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/cooperative/farms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/cooperative/id-station/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cooperative/id-station">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/cooperative/id-station/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/cooperative/members/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cooperative/members/new">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/cooperative/members/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/cooperative/members/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cooperative/members">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/cooperative/members/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/cooperative/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cooperative">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/cooperative/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/cooperative/wallet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cooperative/wallet">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/cooperative/wallet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/data-maintenance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/data-maintenance">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/data-maintenance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/expenses/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expenses/new">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/expenses/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/expenses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expenses">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/expenses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/fund-sources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fund-sources">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/fund-sources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/hr/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/attendance">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/hr/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/hr/biometrics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/biometrics">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/hr/biometrics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/hr/kiosk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/kiosk">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/hr/kiosk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/hr/payroll/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/payroll">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/hr/payroll/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/inventory/adjustments/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/adjustments/[id]">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/inventory/adjustments/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/inventory/adjustments/[id]/verify/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/adjustments/[id]/verify">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/inventory/adjustments/[id]/verify/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/inventory/adjustments/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/adjustments/new">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/inventory/adjustments/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/inventory/adjustments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/adjustments">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/inventory/adjustments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/inventory/movements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/movements">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/inventory/movements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/inventory/transfers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/transfers/[id]">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/inventory/transfers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/inventory/transfers/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/transfers/new">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/inventory/transfers/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/inventory/transfers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory/transfers">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/inventory/transfers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/pos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pos">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/pos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/purchase-orders/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase-orders/[id]/edit">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/purchase-orders/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/purchase-orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase-orders/[id]">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/purchase-orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/purchase-orders/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase-orders/new">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/purchase-orders/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/purchase-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase-orders">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/purchase-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/receiving-vouchers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/receiving-vouchers/[id]">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/receiving-vouchers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/receiving-vouchers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/receiving-vouchers">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/receiving-vouchers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/roadmap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/roadmap">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/roadmap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/roles">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/sales-history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales-history">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/sales-history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/sales-orders/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales-orders/[id]/edit">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/sales-orders/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/sales-orders/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales-orders/new">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/sales-orders/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/sales-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales-orders">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/sales-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/settings/audit-logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/audit-logs">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/settings/audit-logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/suppliers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/suppliers">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/suppliers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/test-auth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-auth">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/test-auth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/users">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/warehouses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouses">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/warehouses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/cooperative-analyzer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cooperative-analyzer">> = Specific
  const handler = {} as typeof import("../../../app/(main)/cooperative-analyzer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(main)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/roles">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/users">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/debug-products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/debug-products">> = Specific
  const handler = {} as typeof import("../../../app/debug-products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/portal/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/portal/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/portal/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portal/login">> = Specific
  const handler = {} as typeof import("../../../app/portal/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/alerts/counts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alerts/counts">> = Specific
  const handler = {} as typeof import("../../../app/api/alerts/counts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alerts">> = Specific
  const handler = {} as typeof import("../../../app/api/alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ap/[id]/payment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ap/[id]/payment">> = Specific
  const handler = {} as typeof import("../../../app/api/ap/[id]/payment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ap/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ap/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/ap/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ap/aging-report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ap/aging-report">> = Specific
  const handler = {} as typeof import("../../../app/api/ap/aging-report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ap/payment/batch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ap/payment/batch">> = Specific
  const handler = {} as typeof import("../../../app/api/ap/payment/batch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ap/payment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ap/payment">> = Specific
  const handler = {} as typeof import("../../../app/api/ap/payment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ap/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ap">> = Specific
  const handler = {} as typeof import("../../../app/api/ap/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/approvals/[id]/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/approvals/[id]/approve">> = Specific
  const handler = {} as typeof import("../../../app/api/approvals/[id]/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/approvals/[id]/reject/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/approvals/[id]/reject">> = Specific
  const handler = {} as typeof import("../../../app/api/approvals/[id]/reject/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/approvals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/approvals">> = Specific
  const handler = {} as typeof import("../../../app/api/approvals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ar/[id]/payment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ar/[id]/payment">> = Specific
  const handler = {} as typeof import("../../../app/api/ar/[id]/payment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ar/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ar/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/ar/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ar/aging-report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ar/aging-report">> = Specific
  const handler = {} as typeof import("../../../app/api/ar/aging-report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ar/payment/batch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ar/payment/batch">> = Specific
  const handler = {} as typeof import("../../../app/api/ar/payment/batch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ar/payment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ar/payment">> = Specific
  const handler = {} as typeof import("../../../app/api/ar/payment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ar/payments-report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ar/payments-report">> = Specific
  const handler = {} as typeof import("../../../app/api/ar/payments-report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ar">> = Specific
  const handler = {} as typeof import("../../../app/api/ar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/audit-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit-logs">> = Specific
  const handler = {} as typeof import("../../../app/api/audit-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/change-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/change-password">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/change-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/forgot-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/forgot-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/verify-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/verify-email">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/verify-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/branches/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/branches/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/branches/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/branches/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/branches">> = Specific
  const handler = {} as typeof import("../../../app/api/branches/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cooperative/farms/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cooperative/farms/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/cooperative/farms/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cooperative/farms/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cooperative/farms">> = Specific
  const handler = {} as typeof import("../../../app/api/cooperative/farms/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cooperative/id-templates/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cooperative/id-templates/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/cooperative/id-templates/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cooperative/id-templates/[id]/set-default/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cooperative/id-templates/[id]/set-default">> = Specific
  const handler = {} as typeof import("../../../app/api/cooperative/id-templates/[id]/set-default/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cooperative/id-templates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cooperative/id-templates">> = Specific
  const handler = {} as typeof import("../../../app/api/cooperative/id-templates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cooperative/initiatives/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cooperative/initiatives/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/cooperative/initiatives/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cooperative/initiatives/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cooperative/initiatives">> = Specific
  const handler = {} as typeof import("../../../app/api/cooperative/initiatives/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cooperative/leaderboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cooperative/leaderboard">> = Specific
  const handler = {} as typeof import("../../../app/api/cooperative/leaderboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cooperative/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cooperative/me">> = Specific
  const handler = {} as typeof import("../../../app/api/cooperative/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cooperative/members/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cooperative/members/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/cooperative/members/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cooperative/members/[id]/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cooperative/members/[id]/stats">> = Specific
  const handler = {} as typeof import("../../../app/api/cooperative/members/[id]/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cooperative/members/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cooperative/members">> = Specific
  const handler = {} as typeof import("../../../app/api/cooperative/members/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cooperative/membership-types/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cooperative/membership-types/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/cooperative/membership-types/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cooperative/membership-types/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cooperative/membership-types">> = Specific
  const handler = {} as typeof import("../../../app/api/cooperative/membership-types/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cooperative/proposals/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cooperative/proposals/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/cooperative/proposals/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cooperative/proposals/[id]/vote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cooperative/proposals/[id]/vote">> = Specific
  const handler = {} as typeof import("../../../app/api/cooperative/proposals/[id]/vote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cooperative/proposals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cooperative/proposals">> = Specific
  const handler = {} as typeof import("../../../app/api/cooperative/proposals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cooperative/tasks/[id]/assign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cooperative/tasks/[id]/assign">> = Specific
  const handler = {} as typeof import("../../../app/api/cooperative/tasks/[id]/assign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cooperative/tasks/[id]/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cooperative/tasks/[id]/complete">> = Specific
  const handler = {} as typeof import("../../../app/api/cooperative/tasks/[id]/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cooperative/tasks/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cooperative/tasks/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/cooperative/tasks/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cooperative/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cooperative/tasks">> = Specific
  const handler = {} as typeof import("../../../app/api/cooperative/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cooperative/wallets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cooperative/wallets">> = Specific
  const handler = {} as typeof import("../../../app/api/cooperative/wallets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cooperative/wallets/transactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cooperative/wallets/transactions">> = Specific
  const handler = {} as typeof import("../../../app/api/cooperative/wallets/transactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/customers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customers/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/customers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/customers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/customers">> = Specific
  const handler = {} as typeof import("../../../app/api/customers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/dashboard/aging/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/aging">> = Specific
  const handler = {} as typeof import("../../../app/api/dashboard/aging/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/dashboard/branch-comparison/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/branch-comparison">> = Specific
  const handler = {} as typeof import("../../../app/api/dashboard/branch-comparison/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/dashboard/counts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/counts">> = Specific
  const handler = {} as typeof import("../../../app/api/dashboard/counts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/dashboard/kpis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/kpis">> = Specific
  const handler = {} as typeof import("../../../app/api/dashboard/kpis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/dashboard/low-stock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/low-stock">> = Specific
  const handler = {} as typeof import("../../../app/api/dashboard/low-stock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/dashboard/orders-summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/orders-summary">> = Specific
  const handler = {} as typeof import("../../../app/api/dashboard/orders-summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/dashboard/recent-activities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/recent-activities">> = Specific
  const handler = {} as typeof import("../../../app/api/dashboard/recent-activities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/dashboard/sales-trends/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/sales-trends">> = Specific
  const handler = {} as typeof import("../../../app/api/dashboard/sales-trends/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/dashboard/top-products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/top-products">> = Specific
  const handler = {} as typeof import("../../../app/api/dashboard/top-products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/dashboard/warehouse-utilization/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/warehouse-utilization">> = Specific
  const handler = {} as typeof import("../../../app/api/dashboard/warehouse-utilization/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/data-maintenance/[type]/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data-maintenance/[type]/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/data-maintenance/[type]/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/data-maintenance/[type]/[id]/toggle-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data-maintenance/[type]/[id]/toggle-status">> = Specific
  const handler = {} as typeof import("../../../app/api/data-maintenance/[type]/[id]/toggle-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/data-maintenance/[type]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/data-maintenance/[type]">> = Specific
  const handler = {} as typeof import("../../../app/api/data-maintenance/[type]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/dev/seed-user/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/seed-user">> = Specific
  const handler = {} as typeof import("../../../app/api/dev/seed-user/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/dev/seed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/seed">> = Specific
  const handler = {} as typeof import("../../../app/api/dev/seed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/expenses/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expenses/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/expenses/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/expenses/reports/by-category/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expenses/reports/by-category">> = Specific
  const handler = {} as typeof import("../../../app/api/expenses/reports/by-category/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/expenses/reports/by-vendor/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expenses/reports/by-vendor">> = Specific
  const handler = {} as typeof import("../../../app/api/expenses/reports/by-vendor/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/expenses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/expenses">> = Specific
  const handler = {} as typeof import("../../../app/api/expenses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/fund-sources/[id]/adjust/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fund-sources/[id]/adjust">> = Specific
  const handler = {} as typeof import("../../../app/api/fund-sources/[id]/adjust/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/fund-sources/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fund-sources/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/fund-sources/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/fund-sources/[id]/transactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fund-sources/[id]/transactions">> = Specific
  const handler = {} as typeof import("../../../app/api/fund-sources/[id]/transactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/fund-sources/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fund-sources">> = Specific
  const handler = {} as typeof import("../../../app/api/fund-sources/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/fund-sources/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fund-sources/summary">> = Specific
  const handler = {} as typeof import("../../../app/api/fund-sources/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/fund-transfers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fund-transfers">> = Specific
  const handler = {} as typeof import("../../../app/api/fund-transfers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/inventory-adjustments/[id]/copy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory-adjustments/[id]/copy">> = Specific
  const handler = {} as typeof import("../../../app/api/inventory-adjustments/[id]/copy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/inventory-adjustments/[id]/post/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory-adjustments/[id]/post">> = Specific
  const handler = {} as typeof import("../../../app/api/inventory-adjustments/[id]/post/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/inventory-adjustments/[id]/reverse/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory-adjustments/[id]/reverse">> = Specific
  const handler = {} as typeof import("../../../app/api/inventory-adjustments/[id]/reverse/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/inventory-adjustments/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory-adjustments/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/inventory-adjustments/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/inventory-adjustments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory-adjustments">> = Specific
  const handler = {} as typeof import("../../../app/api/inventory-adjustments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/inventory/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/inventory/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/inventory/add-stock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/add-stock">> = Specific
  const handler = {} as typeof import("../../../app/api/inventory/add-stock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/inventory/adjust/batch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/adjust/batch">> = Specific
  const handler = {} as typeof import("../../../app/api/inventory/adjust/batch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/inventory/adjust/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/adjust">> = Specific
  const handler = {} as typeof import("../../../app/api/inventory/adjust/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/inventory/adjustments/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/adjustments/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/inventory/adjustments/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/inventory/adjustments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/adjustments">> = Specific
  const handler = {} as typeof import("../../../app/api/inventory/adjustments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/inventory/average-cost/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/average-cost">> = Specific
  const handler = {} as typeof import("../../../app/api/inventory/average-cost/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/inventory/deduct-stock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/deduct-stock">> = Specific
  const handler = {} as typeof import("../../../app/api/inventory/deduct-stock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/inventory/movements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/movements">> = Specific
  const handler = {} as typeof import("../../../app/api/inventory/movements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/inventory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory">> = Specific
  const handler = {} as typeof import("../../../app/api/inventory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/inventory/stock-level/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/stock-level">> = Specific
  const handler = {} as typeof import("../../../app/api/inventory/stock-level/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/inventory/stock-levels/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/stock-levels">> = Specific
  const handler = {} as typeof import("../../../app/api/inventory/stock-levels/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/inventory/transfer/batch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/transfer/batch">> = Specific
  const handler = {} as typeof import("../../../app/api/inventory/transfer/batch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/inventory/transfer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/transfer">> = Specific
  const handler = {} as typeof import("../../../app/api/inventory/transfer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/inventory/transfers/[id]/post/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/transfers/[id]/post">> = Specific
  const handler = {} as typeof import("../../../app/api/inventory/transfers/[id]/post/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/inventory/transfers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/transfers/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/inventory/transfers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/inventory/transfers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inventory/transfers">> = Specific
  const handler = {} as typeof import("../../../app/api/inventory/transfers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../../app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/permissions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/permissions">> = Specific
  const handler = {} as typeof import("../../../app/api/permissions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pos/pending-orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pos/pending-orders">> = Specific
  const handler = {} as typeof import("../../../app/api/pos/pending-orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pos/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pos/products">> = Specific
  const handler = {} as typeof import("../../../app/api/pos/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pos/sales/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pos/sales/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/pos/sales/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pos/sales/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pos/sales">> = Specific
  const handler = {} as typeof import("../../../app/api/pos/sales/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/pos/sales/today-summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pos/sales/today-summary">> = Specific
  const handler = {} as typeof import("../../../app/api/pos/sales/today-summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/[id]/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[id]/history">> = Specific
  const handler = {} as typeof import("../../../app/api/products/[id]/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/products/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/products">> = Specific
  const handler = {} as typeof import("../../../app/api/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/purchase-orders/[id]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/purchase-orders/[id]/cancel">> = Specific
  const handler = {} as typeof import("../../../app/api/purchase-orders/[id]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/purchase-orders/[id]/receive/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/purchase-orders/[id]/receive">> = Specific
  const handler = {} as typeof import("../../../app/api/purchase-orders/[id]/receive/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/purchase-orders/[id]/receiving-vouchers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/purchase-orders/[id]/receiving-vouchers">> = Specific
  const handler = {} as typeof import("../../../app/api/purchase-orders/[id]/receiving-vouchers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/purchase-orders/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/purchase-orders/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/purchase-orders/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/purchase-orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/purchase-orders">> = Specific
  const handler = {} as typeof import("../../../app/api/purchase-orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/receiving-vouchers/[id]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/receiving-vouchers/[id]/cancel">> = Specific
  const handler = {} as typeof import("../../../app/api/receiving-vouchers/[id]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/receiving-vouchers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/receiving-vouchers/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/receiving-vouchers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/receiving-vouchers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/receiving-vouchers">> = Specific
  const handler = {} as typeof import("../../../app/api/receiving-vouchers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reports/balance-sheet/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/balance-sheet">> = Specific
  const handler = {} as typeof import("../../../app/api/reports/balance-sheet/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reports/best-sellers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/best-sellers">> = Specific
  const handler = {} as typeof import("../../../app/api/reports/best-sellers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reports/cash-flow/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/cash-flow">> = Specific
  const handler = {} as typeof import("../../../app/api/reports/cash-flow/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reports/customer-purchase-history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/customer-purchase-history">> = Specific
  const handler = {} as typeof import("../../../app/api/reports/customer-purchase-history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reports/daily-sales-summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/daily-sales-summary">> = Specific
  const handler = {} as typeof import("../../../app/api/reports/daily-sales-summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reports/discount-promotion-analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/discount-promotion-analytics">> = Specific
  const handler = {} as typeof import("../../../app/api/reports/discount-promotion-analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reports/employee-performance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/employee-performance">> = Specific
  const handler = {} as typeof import("../../../app/api/reports/employee-performance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reports/inventory-value/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/inventory-value">> = Specific
  const handler = {} as typeof import("../../../app/api/reports/inventory-value/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reports/profit-loss/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/profit-loss">> = Specific
  const handler = {} as typeof import("../../../app/api/reports/profit-loss/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reports/receiving-variance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/receiving-variance">> = Specific
  const handler = {} as typeof import("../../../app/api/reports/receiving-variance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reports/sales-agents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/sales-agents">> = Specific
  const handler = {} as typeof import("../../../app/api/reports/sales-agents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reports/sales/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/sales">> = Specific
  const handler = {} as typeof import("../../../app/api/reports/sales/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reports/stock-levels/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/stock-levels">> = Specific
  const handler = {} as typeof import("../../../app/api/reports/stock-levels/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/roadmap/[id]/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/roadmap/[id]/comments">> = Specific
  const handler = {} as typeof import("../../../app/api/roadmap/[id]/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/roadmap/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/roadmap">> = Specific
  const handler = {} as typeof import("../../../app/api/roadmap/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/roles/[id]/permissions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/roles/[id]/permissions">> = Specific
  const handler = {} as typeof import("../../../app/api/roles/[id]/permissions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/roles/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/roles/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/roles/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/roles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/roles">> = Specific
  const handler = {} as typeof import("../../../app/api/roles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sales-history/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sales-history/analytics">> = Specific
  const handler = {} as typeof import("../../../app/api/sales-history/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sales-history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sales-history">> = Specific
  const handler = {} as typeof import("../../../app/api/sales-history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sales-orders/[id]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sales-orders/[id]/cancel">> = Specific
  const handler = {} as typeof import("../../../app/api/sales-orders/[id]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sales-orders/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sales-orders/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/sales-orders/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sales-orders/pending/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sales-orders/pending">> = Specific
  const handler = {} as typeof import("../../../app/api/sales-orders/pending/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/sales-orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sales-orders">> = Specific
  const handler = {} as typeof import("../../../app/api/sales-orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/company/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/company/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/company/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/company/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/company">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/company/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/compare-neon-schemas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/compare-neon-schemas">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/compare-neon-schemas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/database/audit-inventory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/database/audit-inventory">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/database/audit-inventory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/database/backup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/database/backup">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/database/backup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/database/cleanup-test-customers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/database/cleanup-test-customers">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/database/cleanup-test-customers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/database/clear/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/database/clear">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/database/clear/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/database/delete-all-transactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/database/delete-all-transactions">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/database/delete-all-transactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/database/delete-table/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/database/delete-table">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/database/delete-table/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/database/post-all-adjustments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/database/post-all-adjustments">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/database/post-all-adjustments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/database/reset-inventory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/database/reset-inventory">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/database/reset-inventory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/database/restore/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/database/restore">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/database/restore/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/database/seed-test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/database/seed-test">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/database/seed-test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/database/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/database/stats">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/database/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/public/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/public">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/public/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/run-ethel-tests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/run-ethel-tests">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/run-ethel-tests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/run-selenium-tests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/run-selenium-tests">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/run-selenium-tests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/schema/compare/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/schema/compare">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/schema/compare/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/settings/schema/deploy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings/schema/deploy">> = Specific
  const handler = {} as typeof import("../../../app/api/settings/schema/deploy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/suppliers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/suppliers/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/suppliers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/suppliers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/suppliers">> = Specific
  const handler = {} as typeof import("../../../app/api/suppliers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../../app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/user/change-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/change-password">> = Specific
  const handler = {} as typeof import("../../../app/api/user/change-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/user/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/profile">> = Specific
  const handler = {} as typeof import("../../../app/api/user/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/users/[id]/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/[id]/verify">> = Specific
  const handler = {} as typeof import("../../../app/api/users/[id]/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users">> = Specific
  const handler = {} as typeof import("../../../app/api/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/warehouses/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouses/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/warehouses/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/warehouses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/warehouses">> = Specific
  const handler = {} as typeof import("../../../app/api/warehouses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/favicon.ico/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/favicon.ico">> = Specific
  const handler = {} as typeof import("../../../app/favicon.ico/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(dashboard)/purchase-orders/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/purchase-orders">> = Specific
  const handler = {} as typeof import("../../../app/(dashboard)/purchase-orders/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(main)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(main)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(member-portal)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(member-portal)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/portal/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/portal">> = Specific
  const handler = {} as typeof import("../../../app/portal/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
